import type { Database } from 'better-sqlite3';
import {
  getStats,
  getTopNodes,
  getModules,
  getEntryPoints,
  detectCircularDeps,
  getNodesByFile,
} from '@fullerenes/core';
import { generateProjectSummary, initAnthropic } from './anthropic.js';
import { getGeneratedMarkers, writeGeneratedMarkdownFile } from './files.js';

export async function generateClaudeMd(rootDir: string, db: Database) {
  initAnthropic();

  const stats = getStats(db);
  const topNodes = getTopNodes(db, 12);
  const modules = getModules(db, 8);
  const entryPoints = getEntryPoints(db);
  const circular = detectCircularDeps(db);

  // 1. Language determination
  const langKey = Object.keys(stats.languageBreakdown ?? {}).sort(
    (a, b) => (stats.languageBreakdown[b] || 0) - (stats.languageBreakdown[a] || 0)
  )[0] || 'Unknown';

  // 2. Prep context for project summary
  let topFilesContext = '';
  for (const mod of modules) {
    const nodes = getNodesByFile(db, mod.path);
    const topExports = nodes.filter(n => n.outDegree > 0 || n.inDegree > 0).slice(0, 3).map(n => n.name).join(', ');
    topFilesContext += `- ${mod.path}: exports ${topExports}\n`;
  }

  const overview = await generateProjectSummary(
    db,
    langKey,
    stats.fileCount,
    stats.nodeCount,
    modules.length,
    topFilesContext
  );

  // 3. Tree generation (simplified text structure based on tracked files)
  const filesList = db.prepare('SELECT path FROM files').all() as {path:string}[];
  const treeMap: Record<string, number> = {};
  for (const file of filesList) {
      const topDir = file.path.split('/')[0] || '.';
      treeMap[topDir] = (treeMap[topDir] ?? 0) + 1;
  }
  const treeStr = Object.entries(treeMap)
    .sort((a,b) => b[1]-a[1])
    .map(([dir, count]) => `${dir}/ (${count} files)`)
    .join('\n');

  // 4. Render MD
  const dateStr = new Date().toISOString();
  
  let md = `# Codebase context
*Auto-generated by Fullerenes — https://fullerenes.dev*
*Run \`fullerenes index\` to refresh. Last updated: ${dateStr}*

## Overview
${overview}

## Project structure
\`\`\`
${treeStr}
\`\`\`

## Key modules
`;

  for (const mod of modules) {
    const nodes = getNodesByFile(db, mod.path);
    const topNames = nodes.slice(0, 3).map(n => n.name).join(', ');
    md += `- **${mod.path}**\n  - exports: ${topNames || 'none'}\n  - imported by: ${mod.importedByCount} files\n`;
  }

  md += `\n## Core functions and classes\n`;
  for(const node of topNodes) {
     md += `- **${node.name}** (${node.type}) — ${node.filePath}:${node.lineStart}\n`;
     if (node.signature) md += `  - signature: \`${node.signature}\`\n`;
     md += `  - called by: ${node.inDegree} nodes\n`;
  }

  md += `\n## Entry points\n`;
  if (entryPoints.length) {
     for(const ep of entryPoints) {
         md += `- ${ep.filePath} (${ep.outDegree} outgoing edges)\n`;
     }
  } else {
     md += `- None strictly detected (or fully interconnected mesh)\n`;
  }

  md += `\n## Architecture notes\n`;
  if (circular.length > 0) md += `- WARNING: Circular dependencies detected in ${circular.length} core cycles.\n`;
  
  const hubNodes = topNodes.filter(n => n.inDegree > 50);
  if (hubNodes.length > 0) {
     md += `- WARNING: God-nodes detected. ${hubNodes.map(n => n.name).join(', ')} have >50 incoming edges.\n`;
  }
  if (!circular.length && !hubNodes.length) {
      md += `- Graph topology looks cleanly separated.\n`;
  }

  md += `
## For AI agents
When working in this codebase, use the Fullerenes MCP server:
  claude mcp add fullerenes -- npx fullerenes mcp
Key tools available: \`query_codebase\`, \`get_function\`, \`find_entry_points\`, \`search_code\`, \`get_callers\`
`;

  const markers = getGeneratedMarkers();
  const managedContent =
    `<!-- User instructions outside this block are preserved. Fullerenes only rewrites content between ` +
    `\`${markers.start}\` and \`${markers.end}\`. -->\n\n${md}`;

  writeGeneratedMarkdownFile(rootDir, 'CLAUDE.md', managedContent);
  writeGeneratedMarkdownFile(rootDir, 'AGENTS.md', managedContent);
}
