import type { Database } from 'better-sqlite3';
import {
  detectCircularDeps,
  estimateTokenCount,
  getCallers,
  getEntryPoints,
  getModules,
  getNodesByFile,
  getStats,
  getTopNodes,
} from 'fullerenes-core';
import { generateProjectSummary, initAnthropic } from './anthropic.js';
import { getGeneratedMarkers, writeGeneratedMarkdownFile } from './files.js';

export async function generateClaudeMd(rootDir: string, db: Database) {
  initAnthropic();

  const stats = getStats(db);
  const topNodes = getTopNodes(db, 40)
    .filter((node) => node.type !== 'module')
    .slice(0, 12);
  const modules = getModules(db, 8);
  const entryPoints = getEntryPoints(db);
  const circularDeps = detectCircularDeps(db);

  const dominantLanguage =
    Object.entries(stats.languageBreakdown)
      .sort((left, right) => right[1] - left[1])[0]?.[0] ?? 'unknown';

  let topFilesContext = '';
  for (const module of modules) {
    const exports = getNodesByFile(db, module.path)
      .filter((node) => node.type !== 'module')
      .slice(0, 5)
      .map((node) => `${node.name}${node.signature ? ` (${node.signature})` : ''}`)
      .join(', ');
    topFilesContext += `- ${module.path}: ${exports || 'no indexed exports'}\n`;
  }

  const overview = await generateProjectSummary(
    db,
    dominantLanguage,
    stats.fileCount,
    stats.nodeCount,
    modules.length,
    topFilesContext,
  );

  const projectStructure = renderProjectStructure(
    (db.prepare('SELECT path FROM files ORDER BY path ASC').all() as Array<{ path: string }>).map((row) => row.path),
  );

  const dateStr = new Date().toISOString();
  let md = `# Codebase context
*Auto-generated by Fullerenes - https://fullerenes.dev*
*Run \`fullerenes index\` to refresh. Last updated: ${dateStr}*

## Overview
${overview}

## Project structure
\`\`\`
${projectStructure}
\`\`\`

## Key modules
`;

  for (const module of modules) {
    const exports = getNodesByFile(db, module.path)
      .filter((node) => node.type !== 'module')
      .slice(0, 3)
      .map((node) => node.name)
      .join(', ');
    md += `- **${module.path}**\n`;
    md += `  - exports: ${exports || 'none'}\n`;
    md += `  - imported by: ${module.importedByCount} files\n`;
  }

  md += `\n## Core functions and classes\n`;
  for (const node of topNodes) {
    const callers = getCallers(db, node.id, 5);
    md += `- **${node.name}** (${node.type}) - ${node.filePath}:${node.lineStart ?? 1}\n`;
    if (node.signature) {
      md += `  - signature: \`${node.signature}\`\n`;
    }
    md += `  - called by: ${formatCallers(callers)}\n`;
  }

  md += `\n## Entry points\n`;
  if (entryPoints.length) {
    for (const entryPoint of entryPoints) {
      md += `- ${entryPoint.filePath}:${entryPoint.lineStart ?? 1} (${entryPoint.outDegree} outgoing edges)\n`;
    }
  } else {
    md += `- None strictly detected.\n`;
  }

  md += `\n## Architecture notes\n`;
  if (circularDeps.length > 0) {
    md += `- Circular dependencies detected:\n`;
    for (const cycle of circularDeps.slice(0, 5)) {
      md += `  - ${cycle.join(' -> ')}\n`;
    }
  } else {
    md += `- No circular dependencies detected.\n`;
  }

  const hubNodes = topNodes.filter((node) => node.inDegree > 50);
  if (hubNodes.length > 0) {
    md += `- High fan-in nodes: ${hubNodes.map((node) => `${node.name} (${node.inDegree})`).join(', ')}.\n`;
  }

  md += `
## For AI agents
When working in this codebase, use the Fullerenes MCP server:
  claude mcp add fullerenes -- npx fullerenes mcp
Key tools available: \`query_codebase\`, \`get_function\`, \`find_entry_points\`, \`search_code\`, \`get_callers\`, \`predict_impact\`

## Token cost
Approximate token cost for this generated context: ${estimateTokenCount(md)} tokens
`;

  const markers = getGeneratedMarkers();
  const managedContent =
    `<!-- User instructions outside this block are preserved. Fullerenes only rewrites content between ` +
    `\`${markers.start}\` and \`${markers.end}\`. -->\n\n${md}`;

  writeGeneratedMarkdownFile(rootDir, 'CLAUDE.md', managedContent);
  writeGeneratedMarkdownFile(rootDir, 'AGENTS.md', managedContent);
}

function renderProjectStructure(paths: string[]): string {
  const counts = new Map<string, number>();

  for (const path of paths) {
    const firstSlash = path.indexOf('/');
    const key = firstSlash === -1 ? path : `${path.slice(0, firstSlash)}/`;
    counts.set(key, (counts.get(key) ?? 0) + 1);
  }

  return Array.from(counts.entries())
    .sort((left, right) => right[1] - left[1] || left[0].localeCompare(right[0]))
    .map(([entry, count]) => `${entry} (${count} files)`)
    .join('\n');
}

function formatCallers(callers: ReturnType<typeof getCallers>): string {
  if (callers.length === 0) {
    return 'no indexed callers';
  }

  return callers
    .map((caller) => `${caller.name} (${caller.filePath}:${caller.lineStart ?? 1})`)
    .join(', ');
}
