import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const GENERATED_START = '<!-- BEGIN FULLERENES -->';
const GENERATED_END = '<!-- END FULLERENES -->';
const GENERATED_BLOCK_PATTERN = /<!-- BEGIN FULLERENES -->[\s\S]*?<!-- END FULLERENES -->\s*/g;

export function writeGeneratedMarkdownFile(
  rootDir: string,
  fileName: 'CLAUDE.md' | 'AGENTS.md',
  generatedContent: string,
): void {
  const targetPath = join(rootDir, fileName);
  const managedBlock = `${GENERATED_START}\n${generatedContent.trim()}\n${GENERATED_END}\n`;

  if (!existsSync(targetPath)) {
    writeFileSync(targetPath, managedBlock);
    return;
  }

  const existing = readFileSync(targetPath, 'utf-8');
  let cleaned = existing.replace(GENERATED_BLOCK_PATTERN, '').trim();
  if (cleaned.includes('Auto-generated by Fullerenes') || cleaned.includes('# Codebase context')) {
    cleaned = '';
  }
  const merged = [cleaned, managedBlock.trimEnd()].filter(Boolean).join('\n\n') + '\n';
  writeFileSync(targetPath, merged);
}

export function getGeneratedMarkers() {
  return {
    start: GENERATED_START,
    end: GENERATED_END,
  };
}
